# Generated by Django 4.2.5 on 2023-09-08 04:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longtitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SO2', models.DecimalField(decimal_places=0, max_digits=18)),
                ('O3', models.DecimalField(decimal_places=0, max_digits=18)),
                ('PM2_5', models.DecimalField(decimal_places=0, max_digits=18)),
                ('PM10', models.DecimalField(decimal_places=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('data_id', models.UUIDField(default=uuid.uuid4, help_text='Unique Id for this data', primary_key=True, serialize=False)),
                ('air_quality_index', models.DecimalField(decimal_places=0, max_digits=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pol_level', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.location')),
                ('pollutant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.pollutant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
