# Generated by Django 3.2.20 on 2023-09-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualitydata',
            name='main_pollutant',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
