# Generated by Django 3.2.20 on 2023-09-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_airqualitydata_main_pollutant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitydata',
            name='main_pollutant',
            field=models.CharField(max_length=10),
        ),
    ]
